### ISSUE TITLE
Downgrade

### ISSUE THREAD

**Issue by ShazaHassanAhmed** [Arbaz-Softagics/commons#1]
Could you downgrade the version of SDK to be compatible with dart SDK 2.5.0? thanks

**Comment by Arbaz-Softagics** [comment]
Thanks for your concern, but i cannot downgrade to dart 2.5 because it's not support Extensions functions. Extensions functions is only available after dart version 2.6.  


Thanks.
Regards, 
CH Arbaz Mateen
On 15-Jan-20 12:56:12 PM, ShazaHassanAhmed <notifications@github.com> wrote:
Could you downgrade the version of SDK to be compatible with dart SDK 2.5.0? thanks
