### ISSUE TITLE
Exception in navigation_functions.dart

### ISSUE THREAD

**Issue by Johann673** [Arbaz-Softagics/commons#8]
Hi,

I have recently updated flutter and now i have an exception during compilation : 

```
Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/commons-0.7.6/lib/src/functions/navigation_functions.dart:27:32: Error: This expression has type 'void' and can't be used.
  return Navigator.of(context).pop<T>(result);
                               ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/commons-0.7.6/lib/src/functions/navigation_functions.dart:31:32: Error: This expression has type 'void' and can't be used.
  return Navigator.of(context).pop<T>(result);
                               ^

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/commons-0.7.6/lib/src/functions/navigation_functions.dart:27:32: Error: This expression has type 'void' and can't be used.
  return Navigator.of(context).pop<T>(result);
                               ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/commons-0.7.6/lib/src/functions/navigation_functions.dart:31:32: Error: This expression has type 'void' and can't be used.
  return Navigator.of(context).pop<T>(result);
                               ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Exception: Gradle task assembleDebug failed with exit code 1
```

Method "pop()" has changes and now it's return null.

Here is my flutter version : 

Flutter 1.17.0-3.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2a7bc389f2 (29 hours ago) • 2020-04-21 20:34:20 -0700
Engine • revision 4c8c31f591
Tools • Dart 2.8.0 (build 2.8.0-dev.20.10)

Thank you.

**Comment by fabiorg74** [comment]
Hi,

i have the same problem here after update Flutter to 1.17 channel master.

I updated commons to the last version (0.7.7+1) and error continue.

Thank you.

**Comment by scrlkx** [comment]
Hi.

I'm having the same issue. Looks like the Flutter did a refactor on the Navigator and broke things! So, **commons will not work the Flutter 1.17**.

We are calling `return Navigator.of(context).pop<T>(result);` in two occasions, both in the `navigation_functions.dart` file. There we are trying to return a flag from the Flutter `.pop` function, but after the latest version, this function is declared as void. So, looks like we need to change two functions: `pop` (at line 24) and `mustPop` (at line 30). 

The `mustPop` function is only called by the `mustPopThis` function and the `mustPopThis` function has no explicit callings. So, I think we can remove both.

Looks like the `pop` function is really necessary because it is used in the documentation, but there is no return expected, maybe we can make it void. This will broke the `popAndPushThis` (line 56), but I'm not seeing no reference or explicit calls to him.

I'm not sure about anything here, but maybe can start here!

**Comment by Arbaz-Softagics** [comment]
Commons upgrade to Flutter 1.17, Please see the change log. Navigator.pop function return type issue resolved. 
Sorry for late reply/fix. Thanks for using [Commons](https://pub.dev/packages/commons)

**Comment by fabiorg74** [comment]
> Commons upgrade to Flutter 1.17, Please see the change log. Navigator.pop function return type issue resolved.
> Sorry for late reply/fix. Thanks for using [Commons](https://pub.dev/packages/commons)

Tksssss Arbaz. Worked perfectly 👍 👍 👍
